### ISSUE TITLE
Domain Pointing

### ISSUE THREAD

**Issue by Vauth** [is-not-cool/registration#26]
### Why does the domain pointing to all of the repos ?
When I set the domain in `vauth/vauth.github.io` repo, It automatically sets for other repos.
- What is this mechanism and how to avoid it (Due to different CORS policy of your domain from github pages)?

**Comment by CuteDog5695** [comment]
I think if you are using the domain on the main repo it will make it the default since the repos usually are directories on the same domain. (Thats kinda my thought, could be wrong)

**Comment by Vauth** [comment]
> I think if you are using the domain on the main repo it will make it the default since the repos usually are directories on the same domain. (Thats kinda my thought, could be wrong)

I tested, you are right.
So how can I set the domain only for one repo.
- Can we set `vauth.github.io/webpage` as `CNAME` ?

**Comment by Vauth** [comment]
> I think if you are using the domain on the main repo it will make it the default since the repos usually are directories on the same domain. (Thats kinda my thought, could be wrong)

I tested, you are right.
Thank you.

**Comment by Vauth** [comment]
> I think if you are using the domain on the main repo it will make it the default since the repos usually are directories on the same domain. (Thats kinda my thought, could be wrong)

I tested, you are right.
Thank you.
